### ISSUE TITLE
No target_ros_msgs files

### ISSUE THREAD

**Issue by yinloonga** [arclab-hku/fast-dodging#2]
Hi, When I compile a package using the `catkin build` command, I encounter some problems:

> fatal errors: 'target_ros_msgs/BoundingBoxes.h' file not found
> #include <target_ros_msgs/BoundingBoxes.h>

Obviously, this repo does not provide all the source files for the original experiment.
In addition to this obvious problem, I also encountered a few other minor problems. 
Therefore, I strongly hope that the author makes sure there are no other problems after downloading it again to another new laptop.

Thanks, Looking forward to your reply

**Comment by MichaelLu-hku** [comment]
Sorry for my carelessness.
I have uploaded the missed package now, you can try it again.
If there are other questions, please don't hesitate to contact us.
