### ISSUE TITLE
about compiled with Clang or GCC tips

### ISSUE THREAD

**Issue by yinloonga** [arclab-hku/fast-dodging#3]
The code was compiled with `GCC` without errors. 
But there is an error with `Clang`.
https://github.com/arclab-hku/fast-dodging/blob/a65fde70cb70813fcf0b410d081b345773d4c979/sort_ros/include/Sort.h#L17
https://github.com/arclab-hku/fast-dodging/blob/a65fde70cb70813fcf0b410d081b345773d4c979/sort_ros/src/Sort.cpp#L5
![Screenshot from 2023-03-01 17-52-44_mosaic](https://user-images.githubusercontent.com/72967324/222105423-35901f2d-a189-471d-9ec2-fbd9daf19eb8.png)
An explanation of the error can be found at [stackoverflow-addition](https://stackoverflow.com/questions/55896356/addition-of-default-argument-on-redeclaration-makes-this-constructor-a-default-c)

> Sort(int maxAge = 5, int minHits = 5, float iouThreshold = 0.15); 
Sort::Sort(int maxAge, int minHits, float iouThreshold)  

Therefore, this detail may not affect much, but please update it together next time

**Comment by MichaelLu-hku** [comment]
Thank you very much for your advise. I haven't found this problem before, and your comment is really useful. I will update it later. 

I am looking forward to further communication with you.
