### ISSUE TITLE
missing files "target_ros_msgs/BoundingBoxes.h" and "target_ros_msgs/CheckForObjectsGoal.h"

### ISSUE THREAD

**Issue by COCOONLINE** [arclab-hku/fast-dodging#7]
@MichaelLu-hku @chenhanpolyu
The pkg does not include "target_ros_msgs/BoundingBoxes.h" and "target_ros_msgs/CheckForObjectsGoal.h".
Please upload these files and please check if other .h files are missing.

Thanks!

**Comment by COCOONLINE** [comment]
It seems all .h files under file named "target_ros_msgs" are missing.

**Comment by MichaelLu-hku** [comment]
The target_ros_msgs package has been included. As for the .h files, will be generated after the package compiled. Maybe you can try build the target_ros_msgs first, and then build other packages.

**Comment by MichaelLu-hku** [comment]
Sorry for my late response, for better communication, I create a QQ group 690764446. You can add it and we can have further communications.

**Comment by COCOONLINE** [comment]
Yes. We built target_ros_msgs first and just solved this problem.
Sure. We'd like to join the group. THX.


> Sorry for my late response, for better communication, I create a QQ group 690764446. You can add it and we can have further communications.
